mongo_db:
  host: 172.18.0.10
  port: 27017
  user: rootuser
  password: rootpwd
  auth_src : admin
  db : qks3_db
qks:
  id: qks3
  ip: 172.18.0.183
  port: 4001
routing: 
  timer : 20
  port : 7000
  ip: 172.18.0.163
redis: 
  user: root
  password: password 
  topic: register3 
  host: 172.18.0.30 
  port: 6379
  db : 3
