mongo_db:
  host: mongodb
  port: 27017
  user: rootuser
  password: rootpwd
  auth_src : admin
  db : qks2_db
qks:
  id: qks2
  ip: 172.18.0.182
  port: 4000
routing: 
  timer : 20
  port : 7000
  ip: 172.18.0.162
redis: 
  user: root
  password: password 
  topic: register2 
  host: redis
  port: 6379
  db : 2
