version: "3.9"

networks:
    frontend:
      ipam:
        config:
          - subnet: 172.16.1.0/24



services: 
    db: 
        image: mongo:latest
        container_name: mongo_auth
        ports: 
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME : rootuser
            MONGO_INITDB_ROOT_PASSWORD : rootpwd
            MONGO_INITDB_DATABASE: admin
        networks:
            frontend:
                ipv4_address: 172.16.1.10

    vault:
        image: vault
        container_name: vault_notls
        ports:
            - 8200:8200
        volumes:
            - ./config_files/vault_config.json:/vault/config/vault_config.json
        cap_add:
            - IPC_LOCK
        entrypoint: vault server -config=/vault/config/vault_config.json
        networks:
            frontend:
                ipv4_address: 172.16.1.20

    redis: 
        image: redis 
        container_name: redis_auth
        ports:
            - 6379:6379
        volumes: 
            - ./config_files/redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        networks:
            frontend:
                ipv4_address: 172.16.1.30

    qks1:
        image: qks:async
        container_name : qks_1
        ports: 
            - 4000:4000 
        command: qks_src/config_files/config.yaml
        networks: 
            frontend: 
                ipv4_address: 172.16.1.250

    routing1:
        image: routing:async
        container_name : routing_1
        ports: 
            - 4000:4000 
        command: routing/config.yaml
        networks: 
            frontend: 
                ipv4_address: 172.16.1.150    



    
    