apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition

metadata:
  name: saes.qks.controller

spec:
  group: qks.controller
  versions: 
    - name: v1 
      served: true 
      storage: true 
      schema: 
        openAPIV3Schema: 
          type: object 
          properties: 
            spec: 
              type: object 
              properties: 
                id: 
                  type: string 
                registration_auto: 
                  type: boolean
  
  scope: Namespaced
  names:
    plural: saes
    singular: sae
    kind: Sae
    shortNames:
     - sae