apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition

metadata:
  name: sae.qks.controller

spec:
  group: qks.controller
  versions: 
    - name: v1 
      served: true 
      storage: true 
      schema: 
        openAPIV3Schema: 
          type: object 
          properties: 
            spec: 
              type: object 
              properties: 
                name: 
                  type: string 
                registration: 
                  type: string
                secret_id: 
                  type: string 
  
  scope: Namespaced
  names:
    plural: saes
    singular: sae
    kind: Sae
    shortNames:
     - sae