mongo_db:
  host: localhost
  port: 27017
  user: rootuser
  password: rootpwd
  auth_src : admin
  db_name : qks1_db

qks:
  KME_ID: qks1
  MAX_KEY_PER_REQUEST: 10
  MAX_KEY_SIZE: 512
  MIN_KEY_SIZE: 128
  MAX_SAE_ID_COUNT: 0
