mongo_db:
  host: localhost
  port: 27017
  user: rootuser
  password: rootpwd
  auth_src : admin
  db_name : qks_db

qks:
  KME_ID: qks1
  KME_IP: 127.0.0.1
  KME_port: 4000
  MAX_KEY_PER_REQUEST: 10
  MAX_KEY_SIZE: 512
  MIN_KEY_SIZE: 128
  MAX_SAE_ID_COUNT: 0

vault: 
  host : localhost
  port : 8200
  token : s.OREZppVgKgng0szwOmiqTR9Y
  key64 : JUrRD1ml2nabyF46Ou73Wxo81XVwcg7qgg6P5u8lxu0=
