version: "3.9"

services: 
    db: 
        image: mongo:latest
        container_name: mongo_auth
        ports: 
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME : rootuser
            MONGO_INITDB_ROOT_PASSWORD : rootpwd
            MONGO_INITDB_DATABASE: admin

    vault:
        image: vault
        container_name: vault_notls
        ports:
            - "8200:8200"
        volumes:
            - ./vault_config.json:/vault/config/vault_config.json
        cap_add:
            - IPC_LOCK
        entrypoint: vault server -config=/vault/config/vault_config.json

    
    