apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secret
type: Opaque
data:
    keycloak-user: YWRtaW4=
    keycloak-password: cGFzc3dvcmQ=
    client_id: cWtzMQ==
    client_secret: NGYwZDFjZDktNGRjOC00NmI5LTk2NTEtZmRmZTExOGY1M2Y4
