apiVersion: v1
kind: ConfigMap
metadata:
  name: qks-configmap
data:
  qks-config: |
    mongo_db:
      host: mongodb-service
      port: 27017
      user: rootuser
      password: rootpwd
      auth_src : admin
      db : qks
    qks:
      id: qks1
      ip: qks-service  # information for the QKDM -> cluster address 
      port: 4000
      max_key_per_request: 20
      max_key_size: 512
      min_key_size: 128
      max_sae_id_count: 0
      indirect_max_key_count: 20
    vault: 
      host : vault-service 
      port : 8200
      token : s.KxoGNMbCu5Yvu7dImOvWlkjZ   # TO BE UPDATED
      key64 : 
        - 9HG2SawbpmZfTZ/w9qjE0REzazQM/5WQm5PaLQ6p/Os=
    redis: 
      user: root
      password: password 
      topic: register
      host: redis-service
      port: 6379
      db : 1
    keycloak: 
      realm: qks
      address: keycloak-service
      port : 8080
