apiVersion: v1
kind: ConfigMap
metadata:
  name: qks-configmap
data:
  qks-config: |
    mongo_db:
      host: mongodb-service
      port: 27017
      user: rootuser
      password: rootpwd
      auth_src : admin
      db : qks1
    qks:
      id: qks1
      ip: qks-service  # information for the QKDM -> cluster address 
      port: 4000
      max_key_per_request: 20
      max_key_size: 512
      min_key_size: 128
      max_sae_id_count: 0
      indirect_max_key_count: 20
    vault: 
      host : vault-service 
      port : 8200
      token : s.6uCzLV3fgNp5tyBRLMdaV6z7    # TO BE UPDATED
      key64 : 
        - 9/KYmfdPbCwPX2OdnF7mt4jKXZ/RV9UazZlny4S2E5SG
        - iJpsgNrIBc/ZjNRAAWAZ0gUcvJBnKMMWBBapAnYPQqge
        - bVJupFLEwJtGA+0o46YdPwoUZQYnzntiKoGLTZghakHP
        - WmKHZdUynBoqjf6KaUGQexEPS12mcvbYIGK27kvNJJCV
        - XaHRDswaaRunn+oYsuYqru2wFLbXvPadcZydsLftgj8g
    redis: 
      user: root
      password: password 
      topic: register1 
      host: redis-service
      port: 6379
      db : 1
    keycloak: 
      realm: qks
      address: keycloak-service
      port : 8080
  keycloak_config: | 
    {
    "web": {
        "auth_uri": "http://keycloak-service:8080/auth/realms/qks/protocol/openid-connect/auth",
        "client_id": "qks1",
        "client_secret" : "4f0d1cd9-4dc8-46b9-9651-fdfe118f53f8",
        "redirect_uris": [
            "http://localhost:4000/oidc_callback"
        ],
        "userinfo_uri": "http://keycloak-service:8080/auth/realms/qks/protocol/openid-connect/userinfo",
        "token_uri": "http://keycloak-service:8080/auth/realms/qks/protocol/openid-connect/token",
        "token_introspection_uri": "http://keycloak-service:8080/auth/realms/qks/protocol/openid-connect/token/introspect"
    }
    }
