mongo_db:
  host: 172.18.0.10
  port: 27017
  user: rootuser
  password: rootpwd
  auth_src : admin
  db : qks3_db
qks:
  id: qks3
  ip: 172.18.0.183
  port: 4000
  max_key_per_request: 20
  max_key_size: 512
  min_key_size: 128
  max_sae_id_count: 0
  indirect_key_size: 256
  indirect_max_key_count: 20
vault: 
  host : 172.18.0.20
  port : 8200
  token : s.SVrGCFg6s5SfaWOKSa4lHDLF
  key64 : vkY52pN+DABjeDaq1lsPbm3OHGYSg/A4UfRwcGN4ygE=
redis: 
  user: root
  password: password 
  topic: register3 
  host: 172.18.0.30
  port: 6379
  db : 3
keycloak: 
  realm: qks
  address: localhost
  port : 8080
