mongo_db:
  host: 172.18.0.10
  port: 27017
  user: rootuser
  password: rootpwd
  auth_src : admin
  db : qks2_db
qks:
  id: qks2
  ip: 172.18.0.182
  port: 4000
  max_key_per_request: 10
  max_key_size: 512
  min_key_size: 128
  max_sae_id_count: 0
  indirect_key_size: 256
  indirect_max_key_count: 10
vault: 
  host : 172.18.0.20
  port : 8200
  token : s.Zh9sFpgtXJeMeXlPz47dZX0k
  key64 : HJUxGf7qFQCuFOO6eytZ3yU03LhixE0ThmXNzp1Bgio=
redis: 
  user: root
  password: password 
  topic: register2 
  host: 172.18.0.30
  port: 6379
  db : 2
