mongo_db:
  host: localhost
  port: 27017
  user: rootuser
  password: rootpwd
  auth_src : admin
  db : qks1_db
qks:
  id: qks1
  ip: 127.0.0.1
  port: 4000
  max_key_per_request: 10
  max_key_size: 512
  min_key_size: 128
  max_sae_id_count: 0
vault: 
  host : localhost
  port : 8200
  token : s.j2UdmgzJjX8gNf2YK2NOFlo2
  key64 : 537ucc/oY+BSqV2CdG97PjFifpMKhS630nuHKyUkdJM=
redis: 
  user: root
  password: password 
  topic: register1 
  host: localhost 
  port: 6379
  db : qks1
