mongo_db:
  host: localhost
  port: 27017
  user: rootuser
  password: rootpwd
  auth_src : admin
  db : qks3_db
qks:
  id: qks3
  ip: 127.0.0.1
  port: 4002
  max_key_per_request: 10
  max_key_size: 512
  min_key_size: 128
  max_sae_id_count: 0
  indirect_key_size: 256
  indirect_max_key_count: 10
vault: 
  host : localhost
  port : 8200
  token : s.G8b0bLPI35KA8yhBWCAfNgA5
  key64 : ZNUv2gMf1sNz0QdnB6+z+buP2sYz53VcYsuax9rl9es=
redis: 
  user: root
  password: password 
  topic: register2 
  host: localhost 
  port: 6379
  db : 2
