mongo_db:
  host: 172.16.1.10
  port: 27017
  user: rootuser
  password: rootpwd
  auth_src : admin
  db : qks1_db
qks:
  id: qks1
  ip: 172.16.1.250
  port: 4000
  max_key_per_request: 10
  max_key_size: 512
  min_key_size: 128
  max_sae_id_count: 0
  indirect_key_size: 256
  indirect_max_key_count: 10
vault: 
  host : 172.16.1.20
  port : 8200
  token : s.GOmImSNVdcHZ5sAYIc7MyflC
  key64 : yt3uzY0g\bsAvaJ8Ax30yAUfsnksOqOJIujtoBR6gBU=
redis: 
  user: root
  password: password 
  topic: register1 
  host: 172.16.1.30
  port: 6379
  db : qks1
