mongo_db:
  host: localhost
  port: 27017
  user: rootuser
  password: rootpwd
  auth_src : admin
  db : qks2_db
qks:
  id: qks2
  ip: 127.0.0.1
  port: 4001
  max_key_per_request: 10
  max_key_size: 512
  min_key_size: 128
  max_sae_id_count: 0
vault: 
  host : localhost
  port : 8200
  token : s.7UgHBdvjAt9F0O7dKEfKtgqs
  key64 : nFBnlc44TUa927gU6Lvhpa4YrMOF3tBsIIszOPoZKwU=
redis: 
  user: root
  password: password 
  topic: register 
  host: localhost 
  port: 6379
  db : qks2
