mongo_db:
  host: 172.18.0.10
  port: 27017
  user: rootuser
  password: rootpwd
  auth_src : admin
  db : qks1_db
qks:
  id: qks1
  ip: 172.18.0.181
  port: 4000
  max_key_per_request: 20
  max_key_size: 512
  min_key_size: 128
  max_sae_id_count: 0
  indirect_max_key_count: 20
vault: 
  host : 172.18.0.20
  port : 8200
  token : s.IvlbsITnckYx3RRxBDC24iLS
  key64 : TjPNkjfDN1hwM6K7kXupVaTLkx6RMXu1crwWGMJucUM=
redis: 
  user: root
  password: password 
  topic: register1 
  host: 172.18.0.30
  port: 6379
  db : 1
keycloak: 
  realm: qks
  address: localhost
  port : 8080
